### ISSUE TITLE
gcc 4.7.1 compile fails

### ISSUE THREAD

**Issue by marguerite** [mathslinux/lwqq#16]
it complains about :

[   46s] lwdb.c:430:5: error: call to function 'lwdb_globaldb_new' without a real prototype [-Werror=unprototyped-calls]

lwdb.c:430:5 actually is:

gdb = lwdb_globaldb_new(global_database_name);

if this line is good, then there must be some failure in function lwdb_globaldb_new, like it returns null.

but your code just free the db when fails...so shellexy and I can't debug out the reason...

so can you please upgrade your gcc and test it? maybe you can solve it  because you know how the db is like...

thanks very much

marguerite

**Comment by mathslinux** [comment]
@marguerite Thank you for testing it. I forgot that global_database_name was a  global variable, 
and lwdb_globaldb_new should be called without any parameter. Have fix it in master tree.

**Comment by marguerite** [comment]
[  102s] cli.c:241:9: error: call to function 'cli_logout' without a real prototype [-Werror=unprototyped-calls]
[  102s] cli.c:211:13: note: 'cli_logout' was declared here
[  102s] cli.c: In function 'main':
[  102s] cli.c:482:5: error: call to function 'cli_logout' without a real prototype [-Werror=unprototyped-calls]
[  102s] cli.c:211:13: note: 'cli_logout' was declared here

...same error here in cli.c

**Comment by mathslinux** [comment]
@marguerite Sorry for delayed reply, have fixed it in master tree.

**Comment by marguerite** [comment]
thanks, now it compiles without any failure. brilliant!
