### ISSUE TITLE
retcode:102 是什么问题

### ISSUE THREAD

**Issue by microcai** [mathslinux/lwqq#18]
wqq/src/liblwqq/msg.c:435 void parse_recvmsg_from_json(LwqqRecvMsgList *, const char *): Parse json object error: {"retcode":102,"errmsg":""}

老遇到这个，102会是神码？

**Comment by btbxbob** [comment]
102似乎是一切正常没有信息的意思

--------Original Message--------

请点击下述附件查看原始邮件。
